backend:
  name: github
  repo: Inago-Digital/stage-micro
  branch: main
  auth_type: implicit
  app_id: Ov23liW6Vo6aYGuKvJLx
  base_url: https://auth.klubstage.cz

media_folder: "static/uploads"
public_folder: "src/_data/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "src/_data/events"
    create: true
    slug: "{{date}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "eTicket Link",
          name: "eTicketLink",
          widget: "string",
          required: false,
        }
      - {
          label: "GoOut Link",
          name: "gooutLink",
          widget: "string",
          required: false,
        }
